import type { Dataset } from "@/lib/admin-data";
import type { ChartKind } from "@/components/admin-charts";
export const ADMIN_SECTIONS:Record<string,{title:string;datasets:Dataset[];groups:Array<[string,string,ChartKind?]>}>={
  overview:{title:"Overview",datasets:[],groups:[["signups","New users","area"],["active","Daily active users","line"],["funnel","Views, saves and application intent","funnel"]]},
  users:{title:"Users",datasets:["users"],groups:[["signups","Signups per day","bar"],["cumulative","Cumulative signups","line"],["completeness","Profile completeness","histogram"],["channel","Preferred channel","donut"],["location","Top locations","horizontal"],["education","Education levels","horizontal"],["field","Fields of study","horizontal"],["languages","Languages","horizontal"]]},
  opportunities:{title:"Opportunities",datasets:["opportunities"],groups:[["opportunity:type","Opportunity types","donut"],["opportunity:status","Listing status",undefined],["opportunity:source","Sources",undefined],["opportunity:origin","Origins",undefined],["opportunity:verification","Verification",undefined],["opportunity:freshness","Freshness",undefined],["top:view","Most viewed","horizontal"],["top:save","Most saved","horizontal"],["top:apply_intent","Most application intents","horizontal"]]},
  organizations:{title:"Organizations",datasets:["organizations"],groups:[["organization:verification","Verification status","donut"]]},
  matching:{title:"Matching",datasets:["matches"],groups:[["matchesPerUser","Matches per user","histogram"],["scores","Match score distribution","histogram"],["funnel","View to save to application intent","funnel"],["type:view","Views by opportunity type",undefined],["type:save","Saves by opportunity type",undefined],["type:apply_intent","Application intent by opportunity type",undefined]]},
  algorithm:{title:"Algorithm",datasets:["match-runs","unmatched-terms"],groups:[["runs","Matching runs over time","line"],["runScores","Historical run score distribution","histogram"],["gates","Candidates excluded by gate","horizontal"],["missing","Most common missing factors in runs","horizontal"],["matchMissing","Missing factors across stored matches","horizontal"]]},
  performance:{title:"Performance",datasets:["request-metrics","web-vitals"],groups:[["latency","Latency by route, milliseconds","horizontal"],["requests","Request volume","area"],["errors","API error rate, percent","line"],...["LCP","INP","CLS","FCP","TTFB"].flatMap((metric): Array<[string,string,ChartKind]> => [[`vitals:${metric}`,`${metric} by route`,"horizontal"],[`vitals-device:${metric}`,`${metric} by device`,"bar"]])]},
  activity:{title:"Activity",datasets:["events","saved"],groups:[["events:view","Views per day","line"],["events:save","Saves per day","line"],["events:click","Clicks per day","line"],["events:apply_intent","Application intents per day","line"],["events:report","Reports per day","line"]]},
  notifications:{title:"Notifications",datasets:["notifications"],groups:[["notifications:delivery","Delivery rate by channel, percent",undefined],["notifications:channel","Channels","donut"],["notifications:status","Delivery status",undefined],["notifications:daily","Notification volume","area"]]},
  feedback:{title:"Feedback inbox",datasets:["feedback"],groups:[["feedback:rating","Ratings","histogram"],["feedback:category","Categories","donut"],["feedback:status","Review status",undefined],["feedback:weekly","Feedback per week","line"]]},
  exports:{title:"Exports",datasets:[],groups:[]},
  "access-log":{title:"Access log",datasets:["access-log"],groups:[]},
};
