import { createHmac, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";
import { USSD_RULES } from "@/config/ussd-rules";
import { AppError } from "@/core/errors/app-error";

export interface UssdCredential { phoneNumber: string; userId: string; pinHash: string; }
export interface UssdCredentialStore { get(phoneNumber: string): Promise<UssdCredential | null>; set(credential: UssdCredential): Promise<void>; }
export class MemoryUssdCredentialStore implements UssdCredentialStore { private readonly values = new Map<string, UssdCredential>(); public async get(phone: string): Promise<UssdCredential | null> { return structuredClone(this.values.get(phone) ?? null); } public async set(value: UssdCredential): Promise<void> { this.values.set(value.phoneNumber, structuredClone(value)); } }
export class RedisUssdCredentialStore implements UssdCredentialStore {
  public constructor(private readonly url = process.env.UPSTASH_REDIS_REST_URL, private readonly token = process.env.UPSTASH_REDIS_REST_TOKEN, private readonly fetcher: typeof fetch = fetch) {}
  private async command(parts: string[]): Promise<unknown> { if (!this.url || !this.token) throw new AppError("USSD credentials are not configured.", 503, "USSD_STORE_NOT_CONFIGURED"); const response = await this.fetcher(this.url, { method: "POST", headers: { authorization: `Bearer ${this.token}`, "content-type": "application/json" }, body: JSON.stringify(parts) }); if (!response.ok) throw new AppError("USSD credential storage failed.", 502, "USSD_STORE_ERROR"); return (await response.json() as { result: unknown }).result; }
  public async get(phone: string): Promise<UssdCredential | null> { const result = await this.command(["GET", `ussd:credential:${phone}`]); return typeof result === "string" ? JSON.parse(result) as UssdCredential : null; }
  public async set(value: UssdCredential): Promise<void> { await this.command(["SET", `ussd:credential:${value.phoneNumber}`, JSON.stringify(value)]); }
}
export function hashUssdPin(pin: string, salt = randomBytes(16).toString("hex")): string { return `${salt}:${scryptSync(pin, salt, 32).toString("hex")}`; }
export function verifyUssdPin(pin: string, encoded: string): boolean { const [salt, hash] = encoded.split(":"); if (!salt || !hash) return false; const expected = Buffer.from(hash, "hex"); const actual = scryptSync(pin, salt, expected.length); return expected.length === actual.length && timingSafeEqual(expected, actual); }
function tokenSecret(): string { const value = process.env.USSD_TOKEN_SECRET; if (!value && process.env.NODE_ENV === "production") throw new AppError("USSD token signing is not configured.", 503, "USSD_AUTH_NOT_CONFIGURED"); return value ?? "local-ussd-secret-not-for-production"; }
export function issueUssdToken(userId: string, phoneNumber: string, now = new Date()): string { const payload = Buffer.from(JSON.stringify({ sub: userId, phone: phoneNumber, scope: "ussd", exp: Math.floor(now.getTime() / 1000) + USSD_RULES.tokenTtlSeconds })).toString("base64url"); const signature = createHmac("sha256", tokenSecret()).update(payload).digest("base64url"); return `${payload}.${signature}`; }
export function verifyUssdToken(token: string, now = new Date()): { userId: string; phoneNumber: string } | null { const [payload, signature] = token.split("."); if (!payload || !signature) return null; const expected = createHmac("sha256", tokenSecret()).update(payload).digest("base64url"); const left = Buffer.from(signature); const right = Buffer.from(expected); if (left.length !== right.length || !timingSafeEqual(left, right)) return null; const value = JSON.parse(Buffer.from(payload, "base64url").toString()) as { sub: string; phone: string; scope: string; exp: number }; return value.scope === "ussd" && value.exp > Math.floor(now.getTime() / 1000) ? { userId: value.sub, phoneNumber: value.phone } : null; }
