export const FEATURE_FLAGS = {
  phaseOneCore: true,
  organizationSubmission: true,
  notifications: true,
  trustReview: true,
  providerTools: true,
  kpiDashboard: true,
  aiMatching: false,
  automatedScraping: false,
  aiComparison: true,
  scrapingShadowMode: true,
  ussd: true,
  ussdPublicRollout: false,
  monetizationReadiness: true,
  payments: false,
  promotedListings: false,
} as const;
