import type { AggregatePoint } from "@/lib/admin-data";
const palette=["#23734d","#f0b52b","#e88773","#43546e","#9b8a61"];
export type ChartKind="line"|"area"|"bar"|"horizontal"|"histogram"|"donut"|"funnel"|"sparkline";
export function AdminChart({title,points,kind="bar"}:{title:string;points:AggregatePoint[];kind?:ChartKind}):React.JSX.Element {
  const data=points.slice(0,90),max=Math.max(1,...data.map(p=>p.value)),total=data.reduce((n,p)=>n+p.value,0);
  const coordinates=data.map((p,i)=>`${20+i*560/Math.max(1,data.length-1)},${160-p.value/max*140}`).join(" ");let angle=0;
  return <figure className="card min-w-0"><figcaption className="mb-4 font-extrabold text-ink">{title}</figcaption>{!data.length?<p className="rounded-xl bg-butter p-4 text-sm text-navy">No data yet.</p>:<>
    <svg viewBox="0 0 600 180" className="h-44 w-full text-leaf" role="img" aria-label={`${title}: ${data.length} categories; values listed below`}>
      {kind==="donut"?data.map((p,i)=>{const length=total?p.value/total*100:0;const offset=angle;angle+=length;return <circle key={p.label} cx="300" cy="90" r="60" pathLength="100" fill="none" stroke={palette[i%palette.length]} strokeWidth="30" strokeDasharray={`${length} ${100-length}`} strokeDashoffset={-offset} transform="rotate(-90 300 90)"/>;}):["line","area","sparkline"].includes(kind)?<>{kind==="area"&&<polygon points={`20,160 ${coordinates} ${20+(data.length-1)*560/Math.max(1,data.length-1)},160`} fill="currentColor" opacity=".15"/>}<polyline points={coordinates} fill="none" stroke="currentColor" strokeWidth="3"/>{data.map((p,i)=><circle key={p.label} cx={20+i*560/Math.max(1,data.length-1)} cy={160-p.value/max*140} r="3" fill="currentColor"/>)}</>:data.map((p,i)=>kind==="horizontal"||kind==="funnel"?<rect key={p.label} x={kind==="funnel"?300-p.value/max*280:20} y={i*170/data.length} width={p.value/max*560} height={Math.max(1,150/data.length)} rx="3" fill={palette[i%palette.length]}/>:<rect key={p.label} x={20+i*560/data.length} y={160-p.value/max*140} width={Math.max(1,500/data.length)} height={p.value/max*140} rx="3" fill={palette[i%palette.length]}/>)}
    </svg><details className="mt-3 text-xs text-navy"><summary className="min-h-8 cursor-pointer">View chart values</summary><div className="max-h-64 overflow-auto"><table className="w-full text-left"><thead><tr><th>Category</th><th>Value</th><th>Samples</th><th>p50</th><th>p95</th><th>p99</th></tr></thead><tbody>{data.map(p=><tr key={p.label}><th className="py-1 pr-2 font-medium">{p.label}</th>{[p.value,p.samples,p.p50,p.p95,p.p99].map((v,i)=><td key={i} className="pr-2">{v==null?"—":Number(v.toFixed(2)).toLocaleString()}</td>)}</tr>)}</tbody></table></div></details>
  </>}</figure>;
}
