import Link from "next/link";
import { ADMIN_COLUMNS } from "@/lib/admin-columns";
import { DATASETS, parseAdminQuery, type Dataset } from "@/lib/admin-data";
import { getRepository } from "@/lib/repository";
import { cellText } from "@/lib/csv";
import { FeedbackEditor } from "@/components/admin-controls";

export async function AdminTable({dataset,params,path}:{dataset:Dataset;params:URLSearchParams;path:string}):Promise<React.JSX.Element>{
  const query=parseAdminQuery(dataset,params),page=await(await getRepository()).adminPage(dataset,query),spec=DATASETS[dataset];
  const columns=[...ADMIN_COLUMNS[spec.table]!,...(dataset==="matches"?["userName","opportunityTitle"]:dataset==="organizations"?["listingCount"]:[])];
  const href=(key:string,value:string)=>{const next=new URLSearchParams(params);next.set(key,value);if(key!=="page")next.delete("page");return `${path}?${next}`;};
  return <section className="card mt-6 min-w-0"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-extrabold capitalize">{dataset.replace(/-/g," ")} <span className="text-sm font-normal text-navy">({page.total.toLocaleString()})</span></h2><a className="button-secondary" href={`/api/v1/admin/export/${dataset}?${params}`}>Download CSV</a></div>
    <form className="my-5 flex flex-wrap items-end gap-3" method="get"><input type="hidden" name="dataset" value={dataset}/><input type="hidden" name="period" value={params.get("period")??"30"}/><label className="min-w-40 flex-1 text-sm">Search<input className="field" name="search" defaultValue={query.search}/></label><label className="text-sm">From<input className="field" type="date" name="from" defaultValue={query.from}/></label><label className="text-sm">Through<input className="field" type="date" name="to" defaultValue={query.to}/></label>
      {spec.filters.map(key=><label key={key} className="w-36 text-sm">{key}{key==="identity"?<select className="field" name={key} defaultValue={query.filters[key]??""}><option value="">All</option><option value="signed-in">Signed in</option><option value="anonymous">Anonymous</option></select>:<input className="field" name={key} defaultValue={query.filters[key]} maxLength={200}/>}</label>)}
      <label className="text-sm">Rows<select className="field" name="size" defaultValue={query.size}>{[25,50,100].map(n=><option key={n}>{n}</option>)}</select></label><input type="hidden" name="sort" value={query.sort}/><input type="hidden" name="direction" value={query.direction}/><button className="button">Apply filters</button></form>
    {!page.rows.length?<p className="rounded-xl bg-butter p-5 text-navy">No data yet for this view.</p>:<div className="max-w-full overflow-x-auto rounded-xl border border-ink/10"><table className="w-full text-left text-sm"><caption className="sr-only">{dataset}, page {query.page}, {page.total} records</caption><thead className="bg-butter"><tr>{dataset==="feedback"&&<th className="p-3">Review</th>}{columns.map(column=><th key={column} className="whitespace-nowrap p-3" scope="col" aria-sort={query.sort===column?(query.direction==="asc"?"ascending":"descending"):undefined}>{(spec.sorts as readonly string[]).includes(column)?<Link href={(()=>{const next=new URLSearchParams(params);next.set("sort",column);next.set("direction",query.sort===column&&query.direction==="desc"?"asc":"desc");next.delete("page");return `${path}?${next}`;})()}>{column} {query.sort===column?(query.direction==="asc"?"↑":"↓"):"↕"}</Link>:column}</th>)}</tr></thead><tbody>{page.rows.map(row=><tr key={String(row.id)} className="border-t border-ink/10 align-top">{dataset==="feedback"&&<td className="p-3"><details><summary className="min-h-11 cursor-pointer font-bold">Review feedback</summary><FeedbackEditor id={String(row.id)} status={String(row.status)} adminNote={row.adminNote as string|null}/></details></td>}{columns.map(column=>{const text=cellText(row[column]);return <td key={column} className="max-w-sm p-3">{text.length>160?<details><summary className="cursor-pointer break-words">{text.slice(0,100)}…</summary><p className="mt-2 whitespace-pre-wrap break-words">{text}</p></details>:<span className="whitespace-pre-wrap break-words">{text||"—"}</span>}</td>;})}</tr>)}</tbody></table></div>}
    <nav aria-label={`${dataset} pages`} className="mt-4 flex items-center justify-between gap-3">{query.page>1?<Link className="button-secondary" href={href("page",String(query.page-1))}>Previous</Link>:<span/>}<span className="text-sm text-navy">Page {query.page} of {Math.max(1,Math.ceil(page.total/query.size))}</span>{query.page*query.size<page.total?<Link className="button-secondary" href={href("page",String(query.page+1))}>Next</Link>:<span/>}</nav>
  </section>;
}
