"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { deviceClass } from "@/lib/route-template";

export function FeedbackForm():React.JSX.Element {
  const [state,setState]=useState<"loading"|"ready"|"sent"|"already"|"unavailable">("loading"),[message,setMessage]=useState(""),[contact,setContact]=useState(false),[rating,setRating]=useState(0),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;void fetch("/api/v1/feedback",{cache:"no-store"}).then(async response=>{if(!response.ok)throw new Error();const data=await response.json();if(active)setState(data.submitted?"already":"ready");}).catch(()=>{if(active)setState("unavailable");});return()=>{active=false;};},[]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError("");if(!rating){setError("Choose a satisfaction rating.");return;}setBusy(true);const data=new FormData(event.currentTarget);try{const response=await fetch("/api/v1/feedback",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({category:data.get("category"),rating,message,contact,contactEmail:contact?String(data.get("contactEmail")??""):"",website:data.get("website"),deviceClass:deviceClass(innerWidth,navigator.userAgent)})});if(response.ok){setState("sent");return;}if(response.status===409){setState("already");return;}setError(response.status===429?"Please try again later. This network has reached its feedback limit.":"We could not save your feedback. Your message is still here; please try again.");}catch{setError("We could not save your feedback. Please try again.");}finally{setBusy(false);}}
  if(state==="loading") return <p className="card mt-6" role="status">Loading feedback form…</p>;
  if(state==="unavailable") return <p className="card mt-6" role="alert">Feedback is unavailable right now. Please reload and try again later.</p>;
  if(state==="already"||state==="sent") return <section className="card mt-6"><h2 className="text-xl font-extrabold" role="status">{state==="already"?"You have already shared feedback. Thank you.":"Thank you for helping improve OppScout."}</h2><Link className="button-secondary mt-5" href="/">Back to home</Link></section>;
  return <form className="card mt-6 space-y-6" onSubmit={submit}>
    <label className="block"><span className="label">Category</span><select name="category" className="field">{[["idea","Idea"],["bug","Bug"],["matching_quality","Matching quality"],["speed","Speed"],["other","Other"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    <fieldset><legend className="label">How satisfied are you?</legend><div className="flex flex-wrap gap-2">{[1,2,3,4,5].map(n=><label key={n} className={`flex min-h-12 min-w-12 cursor-pointer items-center justify-center rounded-xl border-2 ${rating===n?"border-leaf bg-butter":"border-ink/15"}`}><input type="radio" name="rating" value={n} checked={rating===n} onChange={()=>setRating(n)} className="sr-only peer"/><span className="rounded p-1 peer-focus-visible:ring-2 peer-focus-visible:ring-leaf" aria-label={`${n} of 5${n===1?", very dissatisfied":n===5?", very satisfied":""}`}>{n}</span></label>)}</div><p className="mt-2 text-xs text-navy">1 — Very dissatisfied · 5 — Very satisfied</p></fieldset>
    <label className="block"><span className="label">Your feedback</span><textarea className="field min-h-40" value={message} onChange={e=>setMessage(e.target.value)} required minLength={10} maxLength={2000} aria-describedby="feedback-count"/><span id="feedback-count" className="mt-1 block text-right text-xs text-navy">{message.length} / 2000 characters</span></label>
    <label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={contact} onChange={e=>setContact(e.target.checked)} className="size-5"/>You may contact me about this</label>
    {contact&&<label className="block"><span className="label">Email address (optional)</span><input type="email" name="contactEmail" autoComplete="email" className="field" maxLength={254}/></label>}
    <div aria-hidden="true" className="absolute -left-[9999px]"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div>
    {error&&<p role="alert" className="text-sm text-red-800">{error}</p>}<button className="button w-full sm:w-auto" disabled={busy}>{busy?"Sending…":"Share feedback"}</button>
    <p className="text-xs leading-5 text-navy">The OppScout team reads submissions. We store your feedback, rating, device category, app version, and protected visitor and network identifiers to prevent repeated submissions. If signed in, your feedback is linked to your profile. An email address is stored only if you choose to be contacted. Each visitor may submit once.</p>
  </form>;
}
