"use client";

import { useState } from "react";

export function OpportunityForm({ organizationId }: { organizationId: string }): React.JSX.Element {
  const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setMessage("Sending for review…");
    const body = { title: String(data.get("title")), organizationId, category: String(data.get("category")), description: String(data.get("description")), eligibility: { educationLevels: String(data.get("educationLevels")).split(",").map((v) => v.trim()).filter(Boolean), fieldsOfStudy: String(data.get("fieldsOfStudy")).split(",").map((v) => v.trim()).filter(Boolean) }, requiredSkills: String(data.get("requiredSkills")).split(",").map((v) => v.trim()).filter(Boolean), preferredSkills: [], location: String(data.get("location")), workMode: String(data.get("workMode")), deadline: new Date(String(data.get("deadline"))).toISOString(), applicationMethod: String(data.get("applicationMethod")), sourceUrl: String(data.get("sourceUrl")), verificationStatus: "pending", source: "org_submitted", status: "open" };
    const response = await fetch("/api/v1/opportunities", { method: "POST", headers: { "Content-Type": "application/json", "x-oppscout-demo-role": "organization" }, body: JSON.stringify(body) });
    setMessage(response.ok ? "Submitted. It is safely waiting for review." : "Could not submit. Check the official URL and required fields.");
    if (response.ok) form.reset();
  }
  return <form onSubmit={submit} className="card mt-6 grid gap-4 md:grid-cols-2"><label><span className="label">Opportunity title</span><input className="field" name="title" required /></label><label><span className="label">Category</span><select className="field" name="category"><option>internship</option><option>scholarship</option><option>job</option><option>fellowship</option></select></label><label className="md:col-span-2"><span className="label">Clear description</span><textarea className="field min-h-32" name="description" required /></label><label><span className="label">Accepted education levels</span><input className="field" name="educationLevels" placeholder="bachelors, diploma" /></label><label><span className="label">Accepted fields</span><input className="field" name="fieldsOfStudy" placeholder="computer science, statistics" /></label><label><span className="label">Required skills</span><input className="field" name="requiredSkills" placeholder="research, communication" /></label><label><span className="label">Location</span><input className="field" name="location" required /></label><label><span className="label">Work mode</span><select className="field" name="workMode"><option value="onsite">On-site</option><option value="hybrid">Hybrid</option><option value="remote">Remote</option></select></label><label><span className="label">Deadline</span><input className="field" type="date" name="deadline" required /></label><label className="md:col-span-2"><span className="label">How to apply</span><input className="field" name="applicationMethod" required /></label><label className="md:col-span-2"><span className="label">Official HTTPS source</span><input className="field" type="url" name="sourceUrl" placeholder="https://…" required /></label><div className="md:col-span-2 flex flex-wrap items-center gap-4"><button className="button">Submit for review</button>{message && <p className="font-bold" role="status">{message}</p>}</div></form>;
}
