import { SCRAPING_RULES } from "@/config/scraping-rules";
import { AppError } from "@/core/errors/app-error";
import type { ShadowCandidate, ShadowOpportunityStore } from "@/services/ingestion/scraping/types";
export class SupabaseShadowOpportunityStore implements ShadowOpportunityStore {
  public constructor(private readonly url = process.env.NEXT_PUBLIC_SUPABASE_URL, private readonly serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY, private readonly fetcher: typeof fetch = fetch) {}
  private headers(contentType = "application/json"): Record<string, string> { if (!this.url || !this.serviceKey) throw new AppError("Shadow storage is not configured.", 503, "SHADOW_STORE_NOT_CONFIGURED"); return { authorization: `Bearer ${this.serviceKey}`, apikey: this.serviceKey, "content-type": contentType }; }
  public async put(candidate: ShadowCandidate): Promise<void> { const response = await this.fetcher(`${this.url}/storage/v1/object/${SCRAPING_RULES.shadowBucket}/${candidate.id}.json`, { method: "POST", headers: { ...this.headers(), "x-upsert": "true" }, body: JSON.stringify(candidate) }); if (!response.ok) throw new AppError(`Shadow storage write failed with ${response.status}.`, 502, "SHADOW_STORE_ERROR"); }
  public async list(): Promise<ShadowCandidate[]> { const listing = await this.fetcher(`${this.url}/storage/v1/object/list/${SCRAPING_RULES.shadowBucket}`, { method: "POST", headers: this.headers(), body: JSON.stringify({ prefix: "", limit: 1000, sortBy: { column: "created_at", order: "desc" } }) }); if (!listing.ok) throw new AppError(`Shadow storage listing failed with ${listing.status}.`, 502, "SHADOW_STORE_ERROR"); const objects = await listing.json() as Array<{ name: string }>; return Promise.all(objects.filter((item) => item.name.endsWith(".json")).map(async (item) => { const response = await this.fetcher(`${this.url}/storage/v1/object/authenticated/${SCRAPING_RULES.shadowBucket}/${item.name}`, { headers: this.headers() }); if (!response.ok) throw new AppError("Shadow artifact could not be read.", 502, "SHADOW_STORE_ERROR"); return response.json() as Promise<ShadowCandidate>; })); }
}
