import Link from "next/link";
import { requirePageAuth } from "@/lib/auth";
import { createServiceRoleClient } from "@/lib/supabase/admin";

export const dynamic = "force-dynamic";

export default async function CandidatesPage(): Promise<React.JSX.Element> {
  const auth = await requirePageAuth(["organization"]);
  const db = createServiceRoleClient();
  const { data: rows } = await db.from("MatchResult").select("userId,score,Opportunity!inner(id,title,organizationId,status,verificationStatus),UserProfile!inner(name,institution,fieldOfStudy,educationLevel,location,skills,shareWithOrganizations,dateOfBirth)").eq("Opportunity.organizationId", auth.organizationId!).eq("Opportunity.status", "open").eq("Opportunity.verificationStatus", "verified").eq("UserProfile.shareWithOrganizations", true).gte("score", Number(process.env.MATCH_RELEVANCE_THRESHOLD ?? 60)).order("score", { ascending: false }).limit(25);
  return <main className="page-shell animate-in"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-extrabold text-ink sm:text-4xl">Candidates</h1><p className="mt-2 text-navy">Consented seekers matched to your open listings.</p></div><Link href="/dashboard/analytics" className="button-secondary">View analytics</Link></div><div className="mt-8 grid gap-4">{(rows ?? []).map((row) => { const profile = Array.isArray(row.UserProfile) ? row.UserProfile[0] : row.UserProfile; const opportunity = Array.isArray(row.Opportunity) ? row.Opportunity[0] : row.Opportunity; const [firstName = "", ...rest] = String(profile?.name ?? "").split(/\s+/); return <article className="card" key={`${row.userId}-${opportunity?.id}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-extrabold text-ink">{firstName} {rest.at(-1)?.charAt(0).toUpperCase() ?? ""}.</h2><p className="text-sm text-navy">{profile?.institution ?? "Institution not provided"} · {profile?.fieldOfStudy ?? "Field not provided"}</p></div><span className="badge-verified">{row.score}% match</span></div><p className="mt-3 text-sm text-navy">{opportunity?.title} · {profile?.location ?? "Location not provided"}</p><p className="mt-2 text-xs text-navy">Top skills: {(profile?.skills ?? []).slice(0, 5).join(", ") || "Not provided"}</p><Link className="button-secondary mt-4 inline-flex" href={`/dashboard/candidates/${row.userId}`}>View candidate</Link></article>; })}{!rows?.length && <section className="card"><p className="text-navy">No consented matched candidates are available yet.</p></section>}</div></main>;
}
